music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :destroy, :new]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new]
end

music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  year       :integer
#  band_id    :integer
#  live       :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :title, presence: true

  belongs_to :band,
    foreign_key: :band_id,
    class_name: :Band
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  origin     :string
#  genre      :string
#  members    :string
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
    foreign_key: :band_id,
    class_name: :Album
end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  before_validation :ensure_session_token

  attr_reader :password

  def generate_session_token
    self.session_token = SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.is_password?(password)
    user
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @bands = Band.all
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to new_band_album_url(:band_id)
    end
  end

  def edit
    @bands = Band.all
    @album = Album.find(params[:id])
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    @band = Band.find_by(id: @album[:band_id])
    render :show
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to edit_album_url
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_url
  end

  def album_params
    params.require(:album).permit(:title, :year, :live, :band_id)
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :current_user_id

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  def require_logout
    redirect_to user_url(current_user) unless logged_out?
  end

  def logged_in?
    !!current_user
  end

  def logged_out?
    !current_user
  end

  def current_user_id
    new_array = []
    email = current_user.email.split("")
    email.each do |letter|
      if letter == "@"
        break
      else
        new_array << letter
      end
    end
    new_array.join("")
  end

  def logout
    session[:session_token] = nil
    current_user.reset_session_token! if current_user
    @current_user
  end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all.sort
    render :index
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  def band_params
    params.require(:band).permit(:name, :origin, :genre, :members)
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_login, only: [:show]
  before_action :require_logout, only: [:new, :create]

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if user
      login(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = ["Wrong username or password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      render :show
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/helpers/bands_helper.rb
module BandsHelper
end

music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

music_app/app/helpers/users_helper.rb
module UsersHelper
end

music_app/app/views/albums/_form.html.erb
<% if action == :new %>
  <% action_url = albums_url %>
  <% submit_button = "Create New Album" %>
  <% title = "" %>
  <% year = ""%>
  <% live = "" %>
<% else %>
  <% action_url = album_url(@album) %>
  <% submit_button = "Edit Album" %>
  <% title = @album.title %>
  <% year = @album.year %>
  <% live = @album.live %>
<% end %>

  <form action="<%= action_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <% if action == :edit %>
      <%= @album.title %>
      <br>
      <br>
      <input type="hidden" name="_method" value="patch">
    <% end %>

    <label>
      Title
      <input type="text" name="album[title]" value="<%= title %>">
      <br><br>
      <% if flash.now[:errors] %>
        <% flash.now[:errors].each do |error| %>
          <%= error %>
        <% end %>
        <br><br>
      <% end %>
      Band Name
      <select name="album[band_id]">
        <option value="">--SELECT FROM BELOW--</option>
        <% @bands.each do |band| %>
          <option value="<%= band.id %>"><%= band.name %></option>
        <% end %>
      </select>
      <br><br>
      Year
      <input type="text" name="album[year]" value="<%= year %>">
      <br><br>
      Live <input type="radio" name="album[live]" value="true">
      Studio <input type="radio" name="album[live]" value="false">
      <br><br><br><br>
      <input type="submit" value="<%= submit_button %>">
      <br><br><br>
    </label>
  </form>

  <form action="<%= bands_url %>" method="get">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" value="Go to All Bands">
  </form>

music_app/app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render 'form', album: @album, action: :edit %>

music_app/app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album, action: :new %>

music_app/app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
<br>
<h3>Band: <%= @band.name %></h3>
<br>
<h3>Year: <%= @album.year %></h3>
<br>
<h3>Live: <%= @album.live %></h3>
<br>
<br>
<br>
<form action="<%= edit_album_url %>" method="get">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Edit Album">
</form>
<br>
<br>
<form action="<%= album_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Delete Album">
</form>

music_app/app/views/bands/_form.html.erb
<% if action == :new %>
  <% action_url = bands_url %>
  <% submit_button = "Create New Band" %>
  <% name = "" %>
  <% origin = ""%>
  <% genre = "" %>
  <% members = "" %>
<% else %>
  <% action_url = band_url(@band) %>
  <% submit_button = "Edit Band" %>
  <% name = @band.name %>
  <% origin = @band.origin %>
  <% genre = @band.genre %>
  <% members = @band.members %>
<% end %>

  <form action="<%= action_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <% if action == :edit %>
      <%= @band.name %>
      <br>
      <br>
      <input type="hidden" name="_method" value="patch">
    <% end %>

    <label>
      Name
      <input type="text" name="band[name]" value="<%= name %>">
      <br>
      <br>
      <% if flash.now[:errors] %>
        <% flash.now[:errors].each do |error| %>
          <%= error %>
        <% end %>
      <% end %>
      <br>
      <br>
      Origin
      <input type="text" name="band[origin]" value="<%= origin %>">
      <br><br><br><br>
      Genre
      <input type="text" name="band[genre]" value="<%= genre %>">
      <br><br><br><br>
      Members
      <input type="text" name="band[members]" value="<%= members %>">
      <br><br><br><br>
      <input type="submit" value="<%= submit_button %>">
      <br><br><br>
    </label>
  </form>

  <form action="<%= bands_url %>" method="get">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" value="Go to All Bands">
  </form>

music_app/app/views/bands/edit.html.erb
<h1>Edit Band</h1>

<%= render 'form', band: @band, action: :edit %>

music_app/app/views/bands/index.html.erb
<h1>All the bands</h1>

<ul>
  <% @bands.each do |band| %>
    <form action="<%= band_url(band) %>" method="get">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="submit" value="<%= band.name %>">
    </form>
    <br>
  <% end %>
</ul>
<br>
<br>
<form action="<%= new_band_url %>" method="get">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Create New Band">
</form>
<br>
<br>
<form action="<%= user_url(current_user) %>" method="get">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Go to Your Page">
</form>

music_app/app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'form', band: @band, action: :new %>

music_app/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<br>
<h3>Origin: <%= @band.origin %></h3>
<br>
<br>
<h3>Genre: <%= @band.genre %></h3>
<br>
<br>
<h3>Members: <%= @band.members %></h3>
<br>
<br>
<form action="<%= edit_band_url %>" method="get">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Edit Band">
</form>
<br>
<br>
<form action="<%= band_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Delete Band">
</form>
<br>
<br>
<form action="<%= bands_url %>" method="get">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Go to All Bands">
</form>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul id="bar">
      <% if !current_user %>
      <form action="<%= new_session_url %>" method="get">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" value="Sign In">
      </form>
      <form action="<%= new_user_url %>" method="get">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" value="Sign Up">
      </form>
      <% else %>
        <form action="<%= session_url %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Sign Out">
        </form>
      <% end %>
    </ul>
    <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<div id="signup">
<h1>Sign Up</h1>
  <form action="<%= users_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>
      Email
      <input type="text" name="user[email]">
      <br>
      <br>
      Password
      <input type="password" name="user[password]">
      <br>
      <br>
      <% if flash.now[:errors] %>
        <% flash.now[:errors].each do |error| %>
          <%= error %>
        <% end %>
        <br>
        <br>
      <% end %>
      <input type="submit" value="Sign Up">
    </label>
  </form>
</div>

music_app/app/views/users/show.html.erb
<h1>Welcome to Music</h1>
<br>
<br>
<%= current_user_id %>
<br>
<br>
<form action="<%= session_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Sign Out">
</form>
<br>
<br>
<form action="<%= bands_url %>" method="get">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Go to All Bands">
</form>